name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2  # Move this here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/umbrella1.jpg
    - images/umbrella.jpg
    - images/sunny.jpg
    - images/d4.png
    - images/rain.png
    - images/sun.png
    - images/blackClouds.png
    - images/clearSky.png
    - images/clouds.png
    - images/blackClouds.png
    - images/heavyRain.png
    - images/clear.png
